### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by lozohcum** [PolymerElements/app-layout#432] opened 2017-03-16 21:12 UTC
### Description
error:   Uncaught exception: Error: ENOENT: no such file or directory, open 'C:\Users\lozohcum\Documents\Repos\polymer-test\bower_compon                    ents\webcomponentsjs\webcomponents-lite.min.js'
error:   Error: ENOENT: no such file or directory, open 'C:\Users\lozohcum\Documents\Repos\polymer-test\bower_components\webcomponentsjs                    \webcomponents-lite.min.js'

**Comment by frankiefu** [comment] 2017-03-22 17:16
duplicate of https://github.com/webcomponents/webcomponentsjs/issues/738

**Closed by frankiefu** 2017-03-22 17:16 UTC
