### ISSUE TITLE
App-header conflicts with modernizr library

### ISSUE THREAD

**Issue by skyred** [PolymerElements/app-layout#314] opened 2016-08-31 03:33 UTC
### Description
When include a modernizr library, the app-header js cannot be initialized. This happens on Chrome but not on Firefox

## Expected outcome

Including a modernizr library shouldn't affect app-header

## Actual outcome

When including a modernizr library in the document header, this line: https://github.com/PolymerElements/app-layout/blob/master/app-header/app-header.html#L487

return this.offsetWidth and this.offsetHeight as 0

### Live Demo
none

### Steps to reproduce

1. Put a `app-header` element in the page.
2. Include a minimal custom build modernizr library (only has 1 feature): https://modernizr.com/download/?touchevents-dontmin 
3. refresh the page and see if the app-header works

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by skyred** [comment] 2016-08-31 03:50
Through debugging.

I found if comment out this line in modernizer library would make app-header work again on Chrome:

````
// Run the test, or use the raw value if it's not a function
        result = is(feature.fn, 'function') ? feature.fn() : feature.fn;
````

**Comment by frankiefu** [comment] 2016-09-02 23:54
It seems to be working fine for me: http://jsbin.com/genibefuga/edit?html,output

**Comment by skyred** [comment] 2016-09-03 13:24
@frankiefu in your example, your are using v2.8.3, which was released in 2014. I couldn't find the latest version v3.3.1 (released in 2016) on cloudflare. 

I tested this minimal and custom build from modernir official site: https://modernizr.com/download/?touchevents-dontmin

**Comment by frankiefu** [comment] 2016-09-06 21:12
This one loads Modernizr v3.3.1 and still seems to be fine: http://jsbin.com/vizamayudu/edit?html,output

**Comment by skyred** [comment] 2016-09-07 11:43
Yes. it does work in your example. Let me go back to debug again. Thanks!!

**Comment by frankiefu** [comment] 2016-09-09 17:34
Closing this, please reopen if you find the issue is in `app-header`.

**Closed by frankiefu** 2016-09-09 17:34 UTC
