### ISSUE TITLE
app-toolbar should change height on small displays

### ISSUE THREAD

**Issue by rejhgadellaa** [PolymerElements/app-layout#482] opened 2017-05-23 06:25 UTC
### Description

According to the Material Guidelines, toolbars should have a height of 56dp on phones and 64dp on larger displays. As far as I can tell, the app-toolbar has a fixed height of 64px.

For convenience, here's the spec, see 'Keylines and spacing'
https://material.io/guidelines/layout/metrics-keylines.html#metrics-keylines-keylines-spacing

### Expected outcome

App-toolbar should change height when displayed on a smaller screen

### Actual outcome

The app-toolbar doesn't resize

### Live Demo

https://www.webcomponents.org/element/PolymerElements/app-layout/elements/app-toolbar

### Steps to reproduce

1. Use polymer-cli to create the starter kit project
2. Run polymer serve --open
3. Resize the window to ~360px width

### Browsers Affected

- [X] Chrome

**Comment by frankiefu** [comment] 2017-05-23 17:17
Duplicate of https://github.com/PolymerElements/app-layout/issues/169

We tried to avoid using media queries inside layout elements because they can be used in many places and for different purposes. I'd recommend using media queries from outside the element.  Something like this:
```
@media (max-width: 600px) {
    app-toolbar {
      height: 56px;
      padding: 0 8px;
    }
}
```
We also have sample code in [Material Design Responsive Toolbar pattern](https://github.com/PolymerElements/app-layout#patterns).

**Closed by frankiefu** 2017-05-23 17:17 UTC
