### ISSUE TITLE
app-drawer scrolling region size incorrect

### ISSUE THREAD

**Issue by F4IF** [PolymerElements/app-layout#224] opened 2016-05-30 23:55 UTC
### Description
Scrolling contents in app-drawer doesn't behave correctly.  I created a new project based on the App Toolbox "Build an app" tutorial.  When I tried to apply scrolling by setting the div height to 100% the scrollbar didn't appear until a significant amount of the items were past the bottom of the window.  I discovered a workaround of setting a bottom margin of 120px for the app-drawer, but this caused the background for the div to show white at the bottom, always 22px above the bottom of the window (regardless of size).  The 120px appears to be directly related to values in app-drawer.html.  Removing the bottom of -120px appears to fix the issue, but may not be a valid fix, especially since it causes the aforementioned background color issue.  As an interesting side note, when I add an app-drawer inside the app-header-layout (for a right side drawer) the scrolling and background color are correct (after adding a margin-top of 64px to compensate for the header).

### Expected outcome

Scrolling should start as soon as items move outside the window, and the div background should fill the region if no padding or margin are applied.

### Actual outcome

By default  the div background fills the region, until a margin is applied to get the scrolling to work correctly.

### Browsers Affected
- Chrome 50.0.2661.102

**Comment by blasten** [comment] 2016-05-31 16:37
did you use 
```css
overflow-y: scroll;
overflow-x: none;
```
?

**Comment by keanulee** [comment] 2016-05-31 17:23
The reason for the `top/bottom: -120px` is so that the drawer/scrim cover up the viewport when it resizes while scrolling on certain mobile browsers (e.g. Safari, Chrome, and probably others). You should still be able to size a full-height scrolling region inside the drawer though since `app-drawer` internally offsets this 120px with `padding-top/bottom`. For example, see https://elements.polymer-project.org/bower_components/app-layout/app-drawer/demo/right-drawer.html (code here: https://github.com/PolymerElements/app-layout/blob/master/app-drawer/demo/right-drawer.html)

**Comment by frankiefu** [comment] 2016-06-02 21:13
As @keanulee mentioned, this is by design.  If you need to make the drawer scrollable, create a wrapper for the scroll content, and apply height and overflow styles to it.
```
<app-drawer>
  <div style="height: 100%; overflow: auto;"></div>
</app-drawer>
```

Closing it.  But let us know if you are still having issue.

**Closed by frankiefu** 2016-06-02 21:13 UTC
