### ISSUE TITLE
Spacing between menu icon and title text is too small in app-drawer-layout

### ISSUE THREAD

**Issue by joshas** [PolymerElements/app-layout#483] opened 2017-05-23 15:58 UTC
### Description

Spacing between menu icon and title text is too small on mobile in `app-drawer-layout`.

### Expected outcome
Spacing between menu icon and title text is as defined in Material guidelines.
![layout_structure_appbar_metrics1](https://cloud.githubusercontent.com/assets/79141/26363270/38e27e86-3fe9-11e7-8935-115815ab3385.png)

### Actual outcome
Title text is too close to menu icon.
![screen shot 2017-05-23 at 18 48 45](https://cloud.githubusercontent.com/assets/79141/26363304/4a92525a-3fe9-11e7-90a9-9f531480cf9b.png)

### Live Demo
https://polymerelements.github.io/app-layout/templates/getting-started/

**Comment by frankiefu** [comment] 2017-05-24 01:17
Duplicate of https://github.com/PolymerElements/app-layout/issues/169

Also see the comment here: https://github.com/PolymerElements/app-layout/issues/482#issuecomment-303471095

So for now you will need to adjust the height/padding/margin to something like this:
```
@media (max-width: 600px) {
  app-toolbar {
    height: 56px;
    padding: 0 8px;
  }
  app-toolbar > [main-title] {
    margin-left: 24px;
  }
}
```

**Closed by frankiefu** 2017-05-24 01:17 UTC
