### ISSUE TITLE
Color for app-drawer background should be removed or set to a css `var`

### ISSUE THREAD

**Issue by skamansam** [PolymerElements/app-layout#442] opened 2017-04-02 02:05 UTC
### Description
The app-drawer element should have unnecessary styles removed from its CSS. This will enable better theming and perhaps more widespread adoption. 

### Expected outcome
The background color can be changed via `app-drawer` CSS selector.

### Actual outcome
Setting the background color for app-drawer has no effect.

### Live Demo
(No Live demo yet, but the project's component page is here: https://github.com/skamansam/questlists/blob/2.0-preview/src/questlists-app.html)

### Steps to reproduce

1. Put an `app-drawer` element in the page.
2. add css to change the element's background color to anything other than #ffffff
3. Open the page in a web browser.

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Safari 9
- [X] Safari 8
- [X] Safari 7
- [X] Edge
- [X] IE 11
- [X] IE 10

**Comment by keanulee** [comment] 2017-04-03 17:08
You can't set `background` on `app-drawer` directly because app-drawer is more than one div element - there's a darker transparent scrim and the actual drawer container. To style the drawer container, you can use the `--app-drawer-content-container` mixin. (e.g. https://github.com/PolymerElements/app-layout/blob/master/app-drawer/demo/left-drawer.html#L44)

**Comment by skamansam** [comment] 2017-04-06 01:06
Thanks! I still don't understand why this has a color set, though. Is there a standard ruleset for polymer elements' styles, and if not, is it being worked on anywhere? (really: Why do some elements have default colors and others use `var`s and still others nothing?)

**Comment by keanulee** [comment] 2017-04-06 02:07
If we don't set a background color, the default value is transparent (https://developer.mozilla.org/en-US/docs/Web/CSS/background) which is most likely undesired.

**Comment by frankiefu** [comment] 2017-06-05 16:56
Closing this as this is expected behavior.

**Closed by frankiefu** 2017-06-05 16:56 UTC
