### ISSUE TITLE
Document body style changing on opening 2nd drawer

### ISSUE THREAD

**Issue by ThilinaTCH** [PolymerElements/app-layout#414] opened 2017-02-23 02:46 UTC
### Description
We are using a drawer layout to place 2 drawers to layout. Left rawer and right drawer. When left drawer opening and closing it's not setting any style to html body. But when right drawer opens there is an issue

### Expected outcome

On opening second drawer should not set html body styles

### Actual outcome

But it set following style,
`style="overflow: hidden;"`
Which disable scrolling of the page

**Comment by keanulee** [comment] 2017-03-10 22:50
When app-drawer is opened and not persistent (i.e. the right drawer), it disables scrolling of the page because the opened drawer is an overlay on the main content. The left drawer is not persistent (e.g. displayed alongside the main content), so it doesn't disable scrolling.

**Comment by frankiefu** [comment] 2017-04-14 20:47
@ThilinaTCH As @keanulee said this is expected behavior.  If you want `app-drawer` without disabling scrolling when it's opened you can set `persistent` on the `app-drawer`.  Here is an example: http://jsbin.com/gozegibozo/edit?html,output

**Comment by frankiefu** [comment] 2017-06-05 16:53
Closing this as this is expected behavior.

**Closed by frankiefu** 2017-06-05 16:53 UTC
