### ISSUE TITLE
app-box not working on scroll

### ISSUE THREAD

**Issue by Lindstrom1989** [PolymerElements/app-layout#307] opened 2016-08-23 16:18 UTC
### Problem
app-box does not work, I have tried in an existing project and also a clean slate. I have imported the element and the parallax scroll effect as instructed. 
The "#backgroundfrontlayer" div seems to have the inline translate applied to it but it does not alter when scrolling.

```
<link rel="import" href="../bower_components/app-layout/app-scroll-effects/effects/parallax-background.html">
<link rel="import" href="../bower_components/app-layout/app-box/app-box.html">

...

<app-box style="height: 600px;" effects="parallax-background">
    <img background src="/themes/custom/d8_base_theme/images/mountains.jpg" style="width:100%; height: 900px" />
</app-box>
```

**Comment by blasten** [comment] 2016-08-24 01:05
Which browser, do you have a jsbin?  I can't reproduce the issue in the demos.

**Comment by Lindstrom1989** [comment] 2016-08-24 10:11
I have managed to find the problem, it seems it will only work if you have an absolutely positioned parent that is set as the scroll-target.
This seems to interfere with things like waterfall toolbar as it seems to need a way to track scrolling too.

In the demo you can see that the top of the image is moving up and down giving the illusion its changing height, is the moving "parallax" div starting from its bottom position?
Rather than translating a div containing an image wouldn't it be better to change the background position with javascript?

**Comment by Lindstrom1989** [comment] 2016-08-24 12:51
Here is an example of the issue, the waterfall header does not scroll away, this element seems to depend on outside configuration to work.
https://github.com/Lindstrom1989/app-box-issue
This is a clone from @Boo-urns

**Comment by blasten** [comment] 2016-08-25 23:16
if you remove that CSS https://github.com/Lindstrom1989/app-box-issue/blob/1c44f51ec83c67b93d1634129b30950731464c31/src/toolbox-layout-app/toolbox-layout-app.html#L85-L93, then you would be scrolling the main document instead of `div#scrollingRegion`. That behavior is also supported, but you would need to remove `scroll-target="scrollingRegion"` from all the app-box elements. Would that answer the question?

**Comment by Lindstrom1989** [comment] 2016-08-26 08:17
@blasten thanks for getting back but this doesn't work.
It fixes the header scroll issue but now the original problem is back where the parallax does not work ^^.

**Comment by blasten** [comment] 2016-08-26 17:42
@Lindstrom1989 It'd be helpful if you can share a repro jsbin or steps to reproduce this issue.

**Comment by Lindstrom1989** [comment] 2016-08-27 18:29
@blasten https://github.com/Lindstrom1989/app-box-issue this shows it

**Comment by blasten** [comment] 2016-08-29 17:53
I see, you are using paper-header-panel.  You *should* use app-header and app-toolbar.  This is how you could fix the issue:

1. Remove `scroll-target="scrollingRegion" ` from https://github.com/Lindstrom1989/app-box-issue/blob/master/src/toolbox-layout-app/toolbox-layout-app.html

2.  Replace https://github.com/Lindstrom1989/app-box-issue/blob/master/index.html#L24-L33 for `app-header` and `app-toolbar`.  You can look at the demos in https://github.com/PolymerElements/app-layout/tree/master/app-header/demo

**Comment by frankiefu** [comment] 2016-09-06 21:46
@Lindstrom1989 I am closing this but please reopen if this is still an issue.

**Closed by frankiefu** 2016-09-06 21:46 UTC
Labels: question
